### ISSUE TITLE
Problem when importing exactly 25 rows

### ISSUE THREAD

**Issue by WSorban** [a-h/ddbimport#6] opened 2021-09-25 22:46 UTC
Importing exactly 25 records, with the following command:
`ddbimport -inputFile variantItems.csv -tableRegion eu-central-1 -tableName variantIds concurrency 30`

will yield the following error

```
{"level":"info","ts":1632609775.8067422,"caller":"cmd/main.go:435","msg":"starting local import","v":"","input":"variantItems.csv","tableRegion":"eu-central-1","tableName":"variantIds"}
{"level":"error","ts":1632609776.1104505,"caller":"cmd/main.go:475","msg":"error executing batch write","v":"","input":"variantItems.csv","tableRegion":"eu-central-1","tableName":"variantIds","workerIndex":1,"error":"batchwriter: ValidationException: 1 validation error detected: Value '{variantIds=[]}' at 'requestItems' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 25, Member must have length greater than or equal to 1]\n\tstatus code: 400, request id: OFQNAKDS1RGLADN1N1FRK26KUBVV4KQNSO5AEMVJF66Q9ASUAAJG","stacktrace":"main.importLocal.func1\n\t/Users/adrian/github.com/a-h/ddbimport/cmd/main.go:475"}
{"level":"info","ts":1632609776.1214213,"caller":"cmd/main.go:505","msg":"complete","v":"","input":"variantItems.csv","tableRegion":"eu-central-1","tableName":"variantIds","records":25,"rps":79,"duration":0.314679}
```

I can provide test data, or more details, as well, if needed.

Thanks for this great tool, by the way!

**Comment by a-h** [comment] 2021-09-26 18:08
Ah thanks, I encountered that error myself just last week (with exactly 1M records), I just hadn't remembered to push the commit. I've fixed it in https://github.com/a-h/ddbimport/commit/e926bcd4f06a147a71847e002b06cf21fdc97e87 

I'll push a new release.

**Comment by a-h** [comment] 2021-09-26 18:31
I've pushed a new release to https://github.com/a-h/ddbimport/releases/tag/v0.0.40

Once you've confirmed it solves it for you, please close the issue. I'm pretty confident it will, because I was running this last week for a client importing test data, and encountered the same problem.

**Comment by a-h** [comment] 2021-09-30 14:41
By the way, it did import all the data, it's just that at the end of the file, it was trying to push an empty set of data to DynamoDB, which throws an error.

**Closed as completed by a-h** 2021-09-30 14:41 UTC
